# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: DÃ©veloppement web 2016 - Simplon Lyon
email: eghaumez@simplon.co
description: > # this means to ignore newlines until "baseurl:"
  In Code We Trust
baseurl: "/support" # the subpath of your site, e.g. /blog
url: "https://simplyon2.github.io/support" # the base hostname & protocol for your site
twitter_username: rxlabz
github_username:  simplyon2

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: pygments
gems:
  - jemoji